### ISSUE TITLE
index

### ISSUE THREAD

**Issue by FabioZTessitore** [AngeloCARAVELLA/MyWebSite#1]
non hai completato proprio niente. Per iniziare comincia a strutturare bene la pagina

**Comment by AngeloCARAVELLA** [comment]
Prof sto leggendo quel sito da voi consigliato in inglese per imparare
l'html , in effetti non mi risulta troppo difficile , nonostante qualche
strano termine vado avanti , l' unica cosa mi chiedevo come mai quando
faccio <title>" .... " </title> non mi esce il titolo come da guida , ma
solo mettendo <h1> "..... " </h1>

2018-04-10 19:17 GMT+02:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by AngeloCARAVELLA** [comment]
A no scusate prof 😂, non avevo letto il paragrafo su "Headings " adesso ho
capito tutto 😂


Il giorno 11 aprile 2018 19:59, Angelo Caravella <sannita6570@gmail.com> ha
scritto:

**Comment by AngeloCARAVELLA** [comment]
Prof , ho visto  che avete chiuso l'issue , ho finito , non devo far nessun commit , vero?

**Comment by FabioZTessitore** [comment]
Devi caricare il lavoro fatto in classe, mancano gli altri file

Il lun 16 apr 2018, 17:07 Angelo_Caravella <notifications@github.com> ha
scritto:
